- name: "Create VPC Security Rule {{ item.protocol }}"
  ibm_is_security_group_rule:
    group: "{{ vpc_security_group.id }}"
    direction: "{{ item.direction }}"
    remote: "{{ item.remote }}"
    tcp:
      - port_max: "{{ item.port_max }}" 
        port_min: "{{ item.port_min }}"
  register: vpc_security_group_rule_tcp_create_output

- name: "Save existing VPC Security Rule {{ item.protocol }} info as fact"
  ansible.builtin.set_fact:
    cacheable: true
    vpc_security_group_rule_tcp: "{{ vpc_security_group_output.resource }}"
  when: vpc_security_group_rule_tcp_create_output.resource.id is defined

- name: "Print VPC Security Rule info {{ item.protocol }}"
  ansible.builtin.debug:
    msg:
      - "VCP Security Rule  : {{ vpc_security_group_rule_tcp }}"

